# Generated by Django 5.1.1 on 2024-09-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_enrollment_delete_enroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='contact_number',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
